on:
  push:
    tags: # Sequence of patterns matched against refs/tags
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
name: Build Artisan's Deployer
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          make build
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          body: |
            - ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: deployer.go-*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
